{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clustershell-console.fullname" . }}
  labels:
    {{- include "clustershell-console.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services", "namespaces", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clustershell-console.fullname" . }}
  labels:
    {{- include "clustershell-console.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clustershell-console.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "clustershell-console.serviceAccountName" . }}
    namespace: {{ include "clustershell-console.namespace" . }}
{{- end }}
