# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clustershell.fullname" . }}-sandbox-runtimeclass
  labels:
    {{- include "clustershell.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clustershell.fullname" . }}-sandbox-runtimeclass
subjects:
  - kind: ServiceAccount
    name: {{ include "clustershell.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
