apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clustershell-inference

resources:
  - quickstart.yaml

commonLabels:
  app.kubernetes.io/part-of: clustershell
  app.kubernetes.io/managed-by: kustomize
